name: clima
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  equatable: ^0.2.4
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  intl: ^0.16.1
  shared_preferences: 0.5.3+1
  geolocator: ^5.0.0
  permission_handler: ^3.1.0
  charts_flutter: ^0.9.0
  flutter_swiper : ^1.1.6
  flutter_native_splash: ^0.1.9
  dcdg: ^2.0.1
  google_fonts: ^1.1.1
  firebase_auth: 
  logger: ^0.9.4
  firebase_core:
  cloud_firestore:

 
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf

  